// <auto-generated />
using System;
using Api.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260903180824_AddBliessteigProvider")]
    partial class AddBliessteigProvider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.AdminAuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("ProviderSlug")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegistrationRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RegistrationRequestId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("AdminAuditEntries");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.HikingTour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCircularPath")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsKidsTour")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLongDistanceTrail")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KomootUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Startpoint")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HikingTours");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.Import", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("HikingToursCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StampingPointsCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.RegistrationNotificationState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegistrationNotificationStates");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.RegistrationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AdminNotificationSentAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Status", "AdminNotificationSentAt");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.SortedStampingPoint", b =>
                {
                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("StampingPointId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Position", "StampingPointId", "TourId");

                    b.HasIndex("StampingPointId");

                    b.HasIndex("TourId");

                    b.ToTable("SortedStampingPoint", (string)null);
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.StampingPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("SeriesId", "Number")
                        .IsUnique();

                    b.HasIndex("SeriesId", "ProviderId");

                    b.ToTable("StampingPoints");

                    b.HasData(
                        new
                        {
                            Id = 5001,
                            Code = 1,
                            ExternalId = "standard-1",
                            Latitude = 50.9982441m,
                            Longitude = 13.9538612m,
                            Name = "Liebethal",
                            Number = 1,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5002,
                            Code = 2,
                            ExternalId = "standard-2",
                            Latitude = 50.9622998m,
                            Longitude = 14.0729352m,
                            Name = "Stadt Wehlen",
                            Number = 2,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5003,
                            Code = 3,
                            ExternalId = "standard-3",
                            Latitude = 50.9788094m,
                            Longitude = 14.1105942m,
                            Name = "Hohnstein",
                            Number = 3,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5004,
                            Code = 4,
                            ExternalId = "standard-4",
                            Latitude = 50.9702213m,
                            Longitude = 14.1206126m,
                            Name = "Brand",
                            Number = 4,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5005,
                            Code = 5,
                            ExternalId = "standard-5",
                            Latitude = 50.9416556m,
                            Longitude = 14.1843440m,
                            Name = "Neumannmühle",
                            Number = 5,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5006,
                            Code = 6,
                            ExternalId = "standard-6",
                            Latitude = 50.9080517m,
                            Longitude = 14.2562470m,
                            Name = "Großer Zschirnstein",
                            Number = 6,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5007,
                            Code = 7,
                            ExternalId = "standard-7",
                            Latitude = 50.8872242m,
                            Longitude = 14.1206126m,
                            Name = "Gohrisch",
                            Number = 7,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5008,
                            Code = 8,
                            ExternalId = "standard-8",
                            Latitude = 50.9255018m,
                            Longitude = 14.0734005m,
                            Name = "Rauenstein",
                            Number = 8,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5101,
                            Code = 1,
                            ExternalId = "standard-1",
                            Latitude = 47.7448200m,
                            Longitude = 8.4462100m,
                            Name = "Stühlingen",
                            Number = 1,
                            ProviderId = 4,
                            SeriesId = 7
                        },
                        new
                        {
                            Id = 5102,
                            Code = 2,
                            ExternalId = "standard-2",
                            Latitude = 47.8398100m,
                            Longitude = 8.5342200m,
                            Name = "Blumberg",
                            Number = 2,
                            ProviderId = 4,
                            SeriesId = 7
                        },
                        new
                        {
                            Id = 5103,
                            Code = 3,
                            ExternalId = "standard-3",
                            Latitude = 47.8443100m,
                            Longitude = 8.3188500m,
                            Name = "Schattenmühle",
                            Number = 3,
                            ProviderId = 4,
                            SeriesId = 7
                        },
                        new
                        {
                            Id = 5104,
                            Code = 4,
                            ExternalId = "standard-4",
                            Latitude = 47.8182400m,
                            Longitude = 8.1637100m,
                            Name = "Oberfischbach (Schluchsee)",
                            Number = 4,
                            ProviderId = 4,
                            SeriesId = 7
                        },
                        new
                        {
                            Id = 5105,
                            Code = 5,
                            ExternalId = "standard-5",
                            Latitude = 47.7601200m,
                            Longitude = 8.1294500m,
                            Name = "St. Blasien",
                            Number = 5,
                            ProviderId = 4,
                            SeriesId = 7
                        },
                        new
                        {
                            Id = 5106,
                            Code = 6,
                            ExternalId = "standard-6",
                            Latitude = 47.7397100m,
                            Longitude = 8.0002100m,
                            Name = "Todtmoos",
                            Number = 6,
                            ProviderId = 4,
                            SeriesId = 7
                        },
                        new
                        {
                            Id = 5201,
                            Code = 1,
                            ExternalId = "standard-1",
                            Latitude = 53.4475100m,
                            Longitude = 9.8322100m,
                            Name = "Fischbek (Hamburg)",
                            Number = 1,
                            ProviderId = 5,
                            SeriesId = 8
                        },
                        new
                        {
                            Id = 5202,
                            Code = 2,
                            ExternalId = "standard-2",
                            Latitude = 53.3275200m,
                            Longitude = 9.8708100m,
                            Name = "Buchholz in der Nordheide",
                            Number = 2,
                            ProviderId = 5,
                            SeriesId = 8
                        },
                        new
                        {
                            Id = 5203,
                            Code = 3,
                            ExternalId = "standard-3",
                            Latitude = 53.2458100m,
                            Longitude = 9.8236200m,
                            Name = "Handeloh",
                            Number = 3,
                            ProviderId = 5,
                            SeriesId = 8
                        },
                        new
                        {
                            Id = 5204,
                            Code = 4,
                            ExternalId = "standard-4",
                            Latitude = 53.1956100m,
                            Longitude = 9.9753100m,
                            Name = "Undeloh",
                            Number = 4,
                            ProviderId = 5,
                            SeriesId = 8
                        },
                        new
                        {
                            Id = 5205,
                            Code = 5,
                            ExternalId = "standard-5",
                            Latitude = 53.1511200m,
                            Longitude = 9.9103200m,
                            Name = "Niederhaverbeck",
                            Number = 5,
                            ProviderId = 5,
                            SeriesId = 8
                        },
                        new
                        {
                            Id = 5206,
                            Code = 6,
                            ExternalId = "standard-6",
                            Latitude = 53.0833100m,
                            Longitude = 9.9986100m,
                            Name = "Bispingen",
                            Number = 6,
                            ProviderId = 5,
                            SeriesId = 8
                        },
                        new
                        {
                            Id = 5207,
                            Code = 7,
                            ExternalId = "standard-7",
                            Latitude = 52.9869200m,
                            Longitude = 9.8389100m,
                            Name = "Soltau",
                            Number = 7,
                            ProviderId = 5,
                            SeriesId = 8
                        },
                        new
                        {
                            Id = 5208,
                            Code = 8,
                            ExternalId = "standard-8",
                            Latitude = 52.9189100m,
                            Longitude = 9.9786200m,
                            Name = "Wietzendorf",
                            Number = 8,
                            ProviderId = 5,
                            SeriesId = 8
                        },
                        new
                        {
                            Id = 5209,
                            Code = 9,
                            ExternalId = "standard-9",
                            Latitude = 52.8753200m,
                            Longitude = 10.1167100m,
                            Name = "Müden (Örtze)",
                            Number = 9,
                            ProviderId = 5,
                            SeriesId = 8
                        },
                        new
                        {
                            Id = 5210,
                            Code = 10,
                            ExternalId = "standard-10",
                            Latitude = 52.9011100m,
                            Longitude = 10.1742100m,
                            Name = "Faßberg",
                            Number = 10,
                            ProviderId = 5,
                            SeriesId = 8
                        },
                        new
                        {
                            Id = 5211,
                            Code = 11,
                            ExternalId = "standard-11",
                            Latitude = 52.8317200m,
                            Longitude = 10.0911200m,
                            Name = "Hermannsburg",
                            Number = 11,
                            ProviderId = 5,
                            SeriesId = 8
                        },
                        new
                        {
                            Id = 5212,
                            Code = 12,
                            ExternalId = "standard-12",
                            Latitude = 52.7344100m,
                            Longitude = 10.2444100m,
                            Name = "Eschede",
                            Number = 12,
                            ProviderId = 5,
                            SeriesId = 8
                        },
                        new
                        {
                            Id = 5213,
                            Code = 13,
                            ExternalId = "standard-13",
                            Latitude = 52.6247200m,
                            Longitude = 10.0811200m,
                            Name = "Celle (Schloss)",
                            Number = 13,
                            ProviderId = 5,
                            SeriesId = 8
                        },
                        new
                        {
                            Id = 5301,
                            Code = 1,
                            ExternalId = "standard-1",
                            Latitude = 51.9082100m,
                            Longitude = 10.4241200m,
                            Name = "Neuwerkkirche Goslar",
                            Number = 1,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5302,
                            Code = 2,
                            ExternalId = "standard-2",
                            Latitude = 51.9367100m,
                            Longitude = 10.4358100m,
                            Name = "Kloster Grauhof",
                            Number = 2,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5303,
                            Code = 3,
                            ExternalId = "standard-3",
                            Latitude = 51.9572200m,
                            Longitude = 10.5398200m,
                            Name = "Kloster Wöltingerode",
                            Number = 3,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5304,
                            Code = 4,
                            ExternalId = "standard-4",
                            Latitude = 51.8601100m,
                            Longitude = 10.6791100m,
                            Name = "Kloster Ilsenburg",
                            Number = 4,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5305,
                            Code = 5,
                            ExternalId = "standard-5",
                            Latitude = 51.8561200m,
                            Longitude = 10.7144200m,
                            Name = "Kloster Drübeck",
                            Number = 5,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5306,
                            Code = 6,
                            ExternalId = "standard-6",
                            Latitude = 51.8488100m,
                            Longitude = 10.7303100m,
                            Name = "St. Laurentius Darlingerode",
                            Number = 6,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5307,
                            Code = 7,
                            ExternalId = "standard-7",
                            Latitude = 51.8262200m,
                            Longitude = 10.7551200m,
                            Name = "Kloster Himmelpforte (Wernigerode)",
                            Number = 7,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5308,
                            Code = 8,
                            ExternalId = "standard-8",
                            Latitude = 51.8061100m,
                            Longitude = 10.9142100m,
                            Name = "Kloster Michaelstein (Blankenburg)",
                            Number = 8,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5309,
                            Code = 9,
                            ExternalId = "standard-9",
                            Latitude = 51.7891200m,
                            Longitude = 10.9575200m,
                            Name = "Bergkirche St. Bartholomäus (Blankenburg)",
                            Number = 9,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5310,
                            Code = 10,
                            ExternalId = "standard-10",
                            Latitude = 51.7547100m,
                            Longitude = 11.0506100m,
                            Name = "Kloster Wendhusen (Thale)",
                            Number = 10,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5311,
                            Code = 11,
                            ExternalId = "standard-11",
                            Latitude = 51.7244200m,
                            Longitude = 11.1364200m,
                            Name = "Stiftskirche St. Cyriakus Gernrode",
                            Number = 11,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5312,
                            Code = 12,
                            ExternalId = "standard-12",
                            Latitude = 51.7871100m,
                            Longitude = 11.1398100m,
                            Name = "Klosterkirche St. Marien (Quedlinburg)",
                            Number = 12,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5313,
                            Code = 13,
                            ExternalId = "standard-13",
                            Latitude = 51.7858200m,
                            Longitude = 11.1369200m,
                            Name = "Stiftskirche St. Servatii (Quedlinburg)",
                            Number = 13,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5314,
                            Code = 14,
                            ExternalId = "standard-14",
                            Latitude = 51.8722100m,
                            Longitude = 11.0421100m,
                            Name = "Spiegelsberge (Halberstadt)",
                            Number = 14,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5315,
                            Code = 15,
                            ExternalId = "standard-15",
                            Latitude = 51.8958200m,
                            Longitude = 11.0483200m,
                            Name = "Dom und Domschatz Halberstadt",
                            Number = 15,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5316,
                            Code = 16,
                            ExternalId = "standard-16",
                            Latitude = 51.8988100m,
                            Longitude = 11.0664100m,
                            Name = "Kloster St. Burchardi (Halberstadt)",
                            Number = 16,
                            ProviderId = 6,
                            SeriesId = 9
                        },
                        new
                        {
                            Id = 5401,
                            Code = 1,
                            ExternalId = "standard-1",
                            Latitude = 49.110405m,
                            Longitude = 7.072924m,
                            Name = "Sarreguemines Bahnhof",
                            Number = 1,
                            ProviderId = 7,
                            SeriesId = 10
                        },
                        new
                        {
                            Id = 5402,
                            Code = 2,
                            ExternalId = "standard-2",
                            Latitude = 49.160345m,
                            Longitude = 7.119782m,
                            Name = "Gräfinthal",
                            Number = 2,
                            ProviderId = 7,
                            SeriesId = 10
                        },
                        new
                        {
                            Id = 5403,
                            Code = 3,
                            ExternalId = "standard-3",
                            Latitude = 49.170907m,
                            Longitude = 7.170777m,
                            Name = "Bebelsheim",
                            Number = 3,
                            ProviderId = 7,
                            SeriesId = 10
                        },
                        new
                        {
                            Id = 5404,
                            Code = 4,
                            ExternalId = "standard-4",
                            Latitude = 49.237008m,
                            Longitude = 7.259220m,
                            Name = "Blieskastel",
                            Number = 4,
                            ProviderId = 7,
                            SeriesId = 10
                        },
                        new
                        {
                            Id = 5405,
                            Code = 5,
                            ExternalId = "standard-5",
                            Latitude = 49.285312m,
                            Longitude = 7.240993m,
                            Name = "Kirkel",
                            Number = 5,
                            ProviderId = 7,
                            SeriesId = 10
                        },
                        new
                        {
                            Id = 5406,
                            Code = 6,
                            ExternalId = "standard-6",
                            Latitude = 49.283315m,
                            Longitude = 7.315955m,
                            Name = "Schwarzenacker",
                            Number = 6,
                            ProviderId = 7,
                            SeriesId = 10
                        },
                        new
                        {
                            Id = 5407,
                            Code = 7,
                            ExternalId = "standard-7",
                            Latitude = 49.321074m,
                            Longitude = 7.344550m,
                            Name = "Homburg",
                            Number = 7,
                            ProviderId = 7,
                            SeriesId = 10
                        },
                        new
                        {
                            Id = 5408,
                            Code = 8,
                            ExternalId = "standard-8",
                            Latitude = 49.362197m,
                            Longitude = 7.312004m,
                            Name = "Jägersburg",
                            Number = 8,
                            ProviderId = 7,
                            SeriesId = 10
                        },
                        new
                        {
                            Id = 5409,
                            Code = 9,
                            ExternalId = "standard-9",
                            Latitude = 49.397474m,
                            Longitude = 7.266016m,
                            Name = "Höchen",
                            Number = 9,
                            ProviderId = 7,
                            SeriesId = 10
                        },
                        new
                        {
                            Id = 5410,
                            Code = 10,
                            ExternalId = "standard-10",
                            Latitude = 49.346269m,
                            Longitude = 7.254470m,
                            Name = "Kulturbahnhof Bexbach",
                            Number = 10,
                            ProviderId = 7,
                            SeriesId = 10
                        });
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.StampingProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataLicenseName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataLicenseUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceAttribution")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRevision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnonymousAccessAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUri")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("StampingProviders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Touringen ist ein im Oktober 2022 von der Funke Mediengruppe in Kooperation mit der Thüringer Tourismus GmbH und regionalen Tourismusverbänden gestartetes System, das Wandererlebnisse mit einem Sammelanreiz verbindet. Nach einer Erweiterung im Juli 2023 umfasst das Netz 430 offizielle Stempelstellen an markanten Aussichtspunkten, Kulturdenkmälern und Naturhighlights in ganz Thüringen sowie im angrenzenden Frankenwald. Neben klassischen Stempel- und Tourenheften gibt es kindgerechte Varianten sowie ein mehrstufiges Abzeichensystem, bei dem Wanderer vom „Hobby Entdecker“ (ab 10 Stempeln) bis zum vollständigen „Touringen Entdecker“ (430 Stempel) mit Pins, Urkunden und einem Eintrag in die „Hall of Fame“ ausgezeichnet werden.",
                            IsAnonymousAccessAllowed = true,
                            Name = "Touringen",
                            Slug = "touringen",
                            WebsiteUri = "https://www.touringen.de/"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "HWN",
                            Description = "Die Harzer Wandernadel ist ein seit 2006 bestehendes Wanderstempelsystem im Harz mit 222 regulären Stempelstellen. Wandernde sammeln die Stempel in einem Wanderpass und können damit verschiedene Leistungsabzeichen bis zum Harzer Wanderkaiser erreichen.",
                            IsAnonymousAccessAllowed = false,
                            Name = "Harzer Wandernadel",
                            Slug = "harzer-wandernadel",
                            WebsiteUri = "https://www.harzer-wandernadel.de/"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "MW",
                            Description = "Der Malerweg im Elbsandsteingebirge der Sächsischen Schweiz gehört zu den traditionsreichsten und beliebtesten Wanderwegen Deutschlands. Der offizielle Wanderpass umfasst 8 Stempelstellen entlang der Etappen.",
                            IsAnonymousAccessAllowed = true,
                            Name = "Malerweg",
                            Slug = "malerweg",
                            WebsiteUri = "https://www.saechsische-schweiz.de/malerweg"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "SST",
                            Description = "Der Schluchtensteig im Naturpark Südschwarzwald führt über 119 Kilometer in 6 Etappen von Stühlingen quer durch spektakuläre Schluchten bis nach Wehr. Entlang der Etappenorte laden Stempelstellen zum Eintragen in den Wanderpass ein.",
                            IsAnonymousAccessAllowed = true,
                            Name = "Schluchtensteig",
                            Slug = "schluchtensteig",
                            WebsiteUri = "https://www.schluchtensteig.de/"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "HNW",
                            Description = "Der Heidschnuckenweg verbindet auf über 220 Kilometern in 13 Etappen Hamburg-Fischbek durch die Lüneburger Heide mit der Residenzstadt Celle. Mit dem offiziellen Wanderpass werden gesammelte Stempel mit Heidschnucken-Wandernadeln belohnt.",
                            IsAnonymousAccessAllowed = true,
                            Name = "Heidschnuckenweg",
                            Slug = "heidschnuckenweg",
                            WebsiteUri = "https://www.heidschnuckenweg.de/"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "HKW",
                            Description = "Der Harzer Klosterwanderweg führt über rund 117 Kilometer entlang geschichtsträchtiger Klöster und Kirchen am Nordrand des Harzes von Goslar bis Halberstadt. 16 markante rote Stempelkästen der Harzer Wandernadel laden zum Sammeln im Begleitheft ein.",
                            IsAnonymousAccessAllowed = true,
                            Name = "Harzer Klosterwanderweg",
                            Slug = "harzer-klosterwanderweg",
                            WebsiteUri = "https://www.harzinfo.de/erlebnisse/harzer-kloester/harzer-klosterwanderweg"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "BS",
                            DataImportedAt = new DateTime(2026, 9, 3, 18, 6, 12, 0, DateTimeKind.Utc),
                            DataLicenseName = "Creative Commons Namensnennung 4.0 International (CC BY 4.0)",
                            DataLicenseUri = "https://creativecommons.org/licenses/by/4.0/",
                            DataSourceAttribution = "Saarpfalz-Touristik, Julia Serov",
                            DataSourceRevision = "f6ccf2af-e2e7-4bd1-becc-4590f8e3456a:2026-09-03T02:08:17",
                            DataSourceUpdatedAt = new DateTime(2026, 9, 3, 2, 8, 17, 0, DateTimeKind.Utc),
                            DataSourceUri = "https://www.saarpfalz-touristik.de/touren/bliessteig-c62caf7374",
                            Description = "Der rund 106 Kilometer lange Bliessteig führt in neun Etappen von Sarreguemines durch den Bliesgau bis nach Bexbach. An den Etappenorten stehen 10 feste Stempelstationen.",
                            IsAnonymousAccessAllowed = true,
                            Name = "Bliessteig",
                            Slug = "bliessteig",
                            WebsiteUri = "https://www.saarpfalz-touristik.de/erlebnisse/wandern/wanderservice/stempelstationen"
                        });
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.StampingSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExpectedPointCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "Slug")
                        .IsUnique();

                    b.ToTable("StampingSeries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpectedPointCount = 430,
                            IsTemporary = false,
                            Name = "Standard",
                            ProviderId = 1,
                            Slug = "standard"
                        },
                        new
                        {
                            Id = 2,
                            ExpectedPointCount = 8,
                            IsTemporary = false,
                            Name = "Naturschätze",
                            ProviderId = 1,
                            Slug = "naturschaetze"
                        },
                        new
                        {
                            Id = 3,
                            ExpectedPointCount = 13,
                            IsTemporary = false,
                            Name = "Familienwanderwege Rhön",
                            ProviderId = 1,
                            Slug = "familienwanderwege-rhoen"
                        },
                        new
                        {
                            Id = 4,
                            IsTemporary = true,
                            Name = "Sonderstempel",
                            ProviderId = 1,
                            Slug = "sonderstempel"
                        },
                        new
                        {
                            Id = 5,
                            ExpectedPointCount = 222,
                            IsTemporary = false,
                            Name = "Standard",
                            ProviderId = 2,
                            Slug = "standard"
                        },
                        new
                        {
                            Id = 6,
                            ExpectedPointCount = 8,
                            IsTemporary = false,
                            Name = "Standard",
                            ProviderId = 3,
                            Slug = "standard"
                        },
                        new
                        {
                            Id = 7,
                            ExpectedPointCount = 6,
                            IsTemporary = false,
                            Name = "Standard",
                            ProviderId = 4,
                            Slug = "standard"
                        },
                        new
                        {
                            Id = 8,
                            ExpectedPointCount = 13,
                            IsTemporary = false,
                            Name = "Standard",
                            ProviderId = 5,
                            Slug = "standard"
                        },
                        new
                        {
                            Id = 9,
                            ExpectedPointCount = 16,
                            IsTemporary = false,
                            Name = "Standard",
                            ProviderId = 6,
                            Slug = "standard"
                        },
                        new
                        {
                            Id = 10,
                            ExpectedPointCount = 10,
                            IsTemporary = false,
                            Name = "Standard",
                            ProviderId = 7,
                            Slug = "standard"
                        });
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultStampingProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleSubject")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultStampingProviderId");

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.UserStampingProvider", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StampingProviderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "StampingProviderId");

                    b.HasIndex("StampingProviderId");

                    b.ToTable("UserStampingProviders");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.UserVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntryCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("HasVisitedTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StampingPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Visited")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StampingPointId")
                        .IsUnique();

                    b.ToTable("UserVisit", (string)null);
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.SortedStampingPoint", b =>
                {
                    b.HasOne("TourEd.Lib.Abstractions.Models.StampingPoint", "StampingPoint")
                        .WithMany()
                        .HasForeignKey("StampingPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourEd.Lib.Abstractions.Models.HikingTour", "Tour")
                        .WithMany("StampingPoints")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StampingPoint");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.StampingPoint", b =>
                {
                    b.HasOne("TourEd.Lib.Abstractions.Models.StampingProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourEd.Lib.Abstractions.Models.StampingSeries", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId", "ProviderId")
                        .HasPrincipalKey("Id", "ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.StampingSeries", b =>
                {
                    b.HasOne("TourEd.Lib.Abstractions.Models.StampingProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.User", b =>
                {
                    b.HasOne("TourEd.Lib.Abstractions.Models.StampingProvider", "DefaultStampingProvider")
                        .WithMany()
                        .HasForeignKey("DefaultStampingProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DefaultStampingProvider");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.UserStampingProvider", b =>
                {
                    b.HasOne("TourEd.Lib.Abstractions.Models.StampingProvider", "StampingProvider")
                        .WithMany("Users")
                        .HasForeignKey("StampingProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourEd.Lib.Abstractions.Models.User", "User")
                        .WithMany("StampingProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StampingProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.UserVisit", b =>
                {
                    b.HasOne("TourEd.Lib.Abstractions.Models.User", null)
                        .WithMany("VisitedStampingPoints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.HikingTour", b =>
                {
                    b.Navigation("StampingPoints");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.StampingProvider", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.User", b =>
                {
                    b.Navigation("StampingProviders");

                    b.Navigation("VisitedStampingPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
