// <auto-generated />
using System;
using Api.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260831133503_AddMalerwegProvider")]
    partial class AddMalerwegProvider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.HikingTour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCircularPath")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsKidsTour")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLongDistanceTrail")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KomootUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Startpoint")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HikingTours");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.Import", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("HikingToursCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StampingPointsCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.SortedStampingPoint", b =>
                {
                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("StampingPointId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Position", "StampingPointId", "TourId");

                    b.HasIndex("StampingPointId");

                    b.HasIndex("TourId");

                    b.ToTable("SortedStampingPoint", (string)null);
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.StampingPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("SeriesId", "Number")
                        .IsUnique();

                    b.HasIndex("SeriesId", "ProviderId");

                    b.ToTable("StampingPoints");

                    b.HasData(
                        new
                        {
                            Id = 5001,
                            Code = 1,
                            ExternalId = "standard-1",
                            Latitude = 50.9982441m,
                            Longitude = 13.9538612m,
                            Name = "Liebethal",
                            Number = 1,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5002,
                            Code = 2,
                            ExternalId = "standard-2",
                            Latitude = 50.9622998m,
                            Longitude = 14.0729352m,
                            Name = "Stadt Wehlen",
                            Number = 2,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5003,
                            Code = 3,
                            ExternalId = "standard-3",
                            Latitude = 50.9788094m,
                            Longitude = 14.1105942m,
                            Name = "Hohnstein",
                            Number = 3,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5004,
                            Code = 4,
                            ExternalId = "standard-4",
                            Latitude = 50.9702213m,
                            Longitude = 14.1206126m,
                            Name = "Brand",
                            Number = 4,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5005,
                            Code = 5,
                            ExternalId = "standard-5",
                            Latitude = 50.9416556m,
                            Longitude = 14.1843440m,
                            Name = "Neumannmühle",
                            Number = 5,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5006,
                            Code = 6,
                            ExternalId = "standard-6",
                            Latitude = 50.9080517m,
                            Longitude = 14.2562470m,
                            Name = "Großer Zschirnstein",
                            Number = 6,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5007,
                            Code = 7,
                            ExternalId = "standard-7",
                            Latitude = 50.8872242m,
                            Longitude = 14.1206126m,
                            Name = "Gohrisch",
                            Number = 7,
                            ProviderId = 3,
                            SeriesId = 6
                        },
                        new
                        {
                            Id = 5008,
                            Code = 8,
                            ExternalId = "standard-8",
                            Latitude = 50.9255018m,
                            Longitude = 14.0734005m,
                            Name = "Rauenstein",
                            Number = 8,
                            ProviderId = 3,
                            SeriesId = 6
                        });
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.StampingProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataLicenseName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataLicenseUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceAttribution")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRevision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnonymousAccessAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUri")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("StampingProviders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Touringen ist ein im Oktober 2022 von der Funke Mediengruppe in Kooperation mit der Thüringer Tourismus GmbH und regionalen Tourismusverbänden gestartetes System, das Wandererlebnisse mit einem Sammelanreiz verbindet. Nach einer Erweiterung im Juli 2023 umfasst das Netz 430 offizielle Stempelstellen an markanten Aussichtspunkten, Kulturdenkmälern und Naturhighlights in ganz Thüringen sowie im angrenzenden Frankenwald. Neben klassischen Stempel- und Tourenheften gibt es kindgerechte Varianten sowie ein mehrstufiges Abzeichensystem, bei dem Wanderer vom „Hobby Entdecker“ (ab 10 Stempeln) bis zum vollständigen „Touringen Entdecker“ (430 Stempel) mit Pins, Urkunden und einem Eintrag in die „Hall of Fame“ ausgezeichnet werden.",
                            IsAnonymousAccessAllowed = true,
                            Name = "Touringen",
                            Slug = "touringen",
                            WebsiteUri = "https://www.touringen.de/"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "HWN",
                            Description = "Die Harzer Wandernadel ist ein seit 2006 bestehendes Wanderstempelsystem im Harz mit 222 regulären Stempelstellen. Wandernde sammeln die Stempel in einem Wanderpass und können damit verschiedene Leistungsabzeichen bis zum Harzer Wanderkaiser erreichen.",
                            IsAnonymousAccessAllowed = false,
                            Name = "Harzer Wandernadel",
                            Slug = "harzer-wandernadel",
                            WebsiteUri = "https://www.harzer-wandernadel.de/"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "MW",
                            Description = "Der Malerweg im Elbsandsteingebirge der Sächsischen Schweiz gehört zu den traditionsreichsten und beliebtesten Wanderwegen Deutschlands. Der offizielle Wanderpass umfasst 8 Stempelstellen entlang der Etappen.",
                            IsAnonymousAccessAllowed = true,
                            Name = "Malerweg",
                            Slug = "malerweg",
                            WebsiteUri = "https://www.saechsische-schweiz.de/malerweg"
                        });
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.StampingSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExpectedPointCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "Slug")
                        .IsUnique();

                    b.ToTable("StampingSeries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpectedPointCount = 430,
                            IsTemporary = false,
                            Name = "Standard",
                            ProviderId = 1,
                            Slug = "standard"
                        },
                        new
                        {
                            Id = 2,
                            ExpectedPointCount = 8,
                            IsTemporary = false,
                            Name = "Naturschätze",
                            ProviderId = 1,
                            Slug = "naturschaetze"
                        },
                        new
                        {
                            Id = 3,
                            ExpectedPointCount = 13,
                            IsTemporary = false,
                            Name = "Familienwanderwege Rhön",
                            ProviderId = 1,
                            Slug = "familienwanderwege-rhoen"
                        },
                        new
                        {
                            Id = 4,
                            IsTemporary = true,
                            Name = "Sonderstempel",
                            ProviderId = 1,
                            Slug = "sonderstempel"
                        },
                        new
                        {
                            Id = 5,
                            ExpectedPointCount = 222,
                            IsTemporary = false,
                            Name = "Standard",
                            ProviderId = 2,
                            Slug = "standard"
                        },
                        new
                        {
                            Id = 6,
                            ExpectedPointCount = 8,
                            IsTemporary = false,
                            Name = "Standard",
                            ProviderId = 3,
                            Slug = "standard"
                        });
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultStampingProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleSubject")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultStampingProviderId");

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.UserVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntryCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("HasVisitedTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StampingPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Visited")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StampingPointId")
                        .IsUnique();

                    b.ToTable("UserVisit", (string)null);
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.SortedStampingPoint", b =>
                {
                    b.HasOne("TourEd.Lib.Abstractions.Models.StampingPoint", "StampingPoint")
                        .WithMany()
                        .HasForeignKey("StampingPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourEd.Lib.Abstractions.Models.HikingTour", "Tour")
                        .WithMany("StampingPoints")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StampingPoint");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.StampingPoint", b =>
                {
                    b.HasOne("TourEd.Lib.Abstractions.Models.StampingProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourEd.Lib.Abstractions.Models.StampingSeries", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId", "ProviderId")
                        .HasPrincipalKey("Id", "ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.StampingSeries", b =>
                {
                    b.HasOne("TourEd.Lib.Abstractions.Models.StampingProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.User", b =>
                {
                    b.HasOne("TourEd.Lib.Abstractions.Models.StampingProvider", "DefaultStampingProvider")
                        .WithMany()
                        .HasForeignKey("DefaultStampingProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultStampingProvider");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.UserVisit", b =>
                {
                    b.HasOne("TourEd.Lib.Abstractions.Models.User", null)
                        .WithMany("VisitedStampingPoints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.HikingTour", b =>
                {
                    b.Navigation("StampingPoints");
                });

            modelBuilder.Entity("TourEd.Lib.Abstractions.Models.User", b =>
                {
                    b.Navigation("VisitedStampingPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
