<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
        <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/ElPlatero/TourEd</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.*" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.*" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.*">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.*" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.*" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Toured.Lib\TourEd.Lib.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Api\obj\Api.csproj.nuget.dgspec.json" />
      <_ContentIncludedByDefault Remove="Api\obj\project.assets.json" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Config\" />
      <Folder Include="wwwroot\css\" />
      <Folder Include="wwwroot\js\" />
    </ItemGroup>

</Project>
